### ISSUE TITLE
Uneven levels of difficulty

### ISSUE THREAD

**Issue by katox** [4clojure/4clojure#222]
After spending considerable time doing the exercises I can say that various people writing problems have wildly different estimates of a problem difficulty for people learning the language.

We can't do much about that but we could gather some data on time actually needed to solve the problem on a successful solution submission. This would allow newcomers (like me two weeks ago) to tackle easier problems first instead of solving older problems first.  Averaging this input over larger group of people could help to find outliers.

Another possibility would be a poll on the difficulty of the problem but that could be problematic because people consider problems harder at the beginning. The method I used to pick problems - after getting really stuck on an "easy" one ;) - was to sort the problem list by number of times solved and then to pick by difficulty. But that is also biased towards older problems.

Just thinking aloud. This enhancement could influence the recommendation order only. I don't think that it should result into directly changing difficulty levels. It would be more like fine tuning. In the end difficulty levels are not that off on average. I can remember only a handful of problems which I would move from hard to easy and vice versa.

**Comment by djtrack16** [comment]
@amcnamara sorry for the delay, i finally submitted the three problems. They should be under my username, djtrack16.

I ran the tests on my own code. Let me know if there are any problems at all with the submission.
Thanks ;)

**Comment by amalloy** [comment]
@djtrack16 Can you include example solutions in this issue conversation?

**Comment by djtrack16** [comment]
@amalloy by example solutions, do you mean actual code, pseudocode, or what is the expected output given certain inputs?

**Comment by amalloy** [comment]
I've solved http://www.4clojure.com/problem/195 myself and marked it approved. It was a fun problem, but editing the problems is a little tedious so I'd be happy if @amcnamara wants to do the rest.

**Comment by amalloy** [comment]
I meant actual code: what solutions did you write that pass your tests. I think that's what @amcnamara meant too. It's just a lot easier to confirm that the test cases are correct if you don't have to solve the problem from scratch youself.

**Comment by djtrack16** [comment]
Makes sense, you can find the solutions here:

https://gist.github.com/djtrack16

They are the only three gists on my page. All these solutions are almost
direct translations from Python.

They all pass, although the parentheses algo is a bit slow (and hacky),
because I am having issues figuring out the idiomatic way to combine the
output at the end without doing an entire tree-seq, which I'm pretty sure
is wholly unnecessary. :)

**Comment by amalloy** [comment]
The parentheses problem is pretty simple really: https://gist.github.com/amalloy/8fdfdda5160581245f23. Your tree-seq/coll?/seq/remove is just a reimplementation of flatten, which is pretty gross *anyway*, to account for the fact that you forgot to concat in the innermost section of code. It's also much easier if you build a sequence instead of a string, and then just convert it all to strings at the end, just because clojure is so much better at handling sequences.

It's hard to be sure because you've mangled all the variable names, but it looks like we use the same algorithm, modulo your confusion about nested sequences.

**Comment by djtrack16** [comment]
our algo is essentially the same (I had already done this problem in
python, but instead of return with yield statements and that was it to make
it "lazy", but maybe there are subtle differences between python's concept
of generators and clojure's concept of lazy sequences, to get a truly
infinite stream in py, you'd have to do a while true i think).
I believe you that clojure is better at handling sequences than strings,
just a language design decision i guess.
Also, I still haven't managed to grok precisely when "partial" is useful or
makes life easier.
I was aware that I was reimplementing flatten, but I tried to use flatten
itself and it didn't work.

why do you think flatten is gross and/or how would you rewrite it? there
must be a cleaner way to get single elements than to walk the entire
tree-seq first and then filter out collections.

**Comment by amalloy** [comment]
Eh, `partial` isn't that amazing: I wrote `(partial apply str)` instead of `#(apply str %)`, and `#(cons \( %)` instead of `(partial cons \()` just as a matter of taste; I don't think it matters terribly which one you prefer, and I can't say why I preferred one over the other.

Flatten is just gross in almost all cases, both because it means you produced data of the wrong shape to begin with and because it's too sensitive to the shape of your data: `(flatten '(((1) 2 ((3 4) 5))))` probably does what you want, but what if instead of numbers you had `[x y]` pairs? `(flatten '((([1 2]) [3 4] (([5 6] [7 8]) [9 10]))))` messes up that internal structure because your data happens to be list-shaped.

As for how to rewrite your solution...well, I'd write mine instead! This is only half a joke: with your minified variable names and over-aggressive indentation it's quite tedious to remember what is going on in your version, even though I know the algorithm is similar to mine. So first, I'd reformat it and remove some extraneous junk: https://gist.github.com/amalloy/2e7af7510d563b4345bd/2d17d2d51e5376ad3a14123bc15ba67ab7bf8952. Now that the two versions are side-by-side, it's not too hard to see what the differences are. The main two are:

- Your function is inconsistent in its return type. Sometimes it returns a single string, other times a pair of strings. Because of this, *each* iteration of your function has to go through this awful set/remove/tree-seq rigamarole just to sort out what's what. No wonder you say it's slow! Compare to mine, which always returns a list of strings (or list of lists of characters, which is much the same), and only has to "flatten" by one level.
- Your recursion is inside-out relative to mine: you're doing something like `[(q (concat ...)) (q (concat ...))]`, where I'm calling `(concat (lazy-recur ...) (lazy-recur ...))`. What this means is that as your call stack gets deep, each "instance" of `q` knows all about the characters that came before it in the list, even though most instances do nothing with `s` but pass it along to the next. Mine, instead, breaks down the problem: each call to `lazy-recur` knows nothing about the characters that came before it, and never joins any strings together. Instead, I "trust" that the function that called me will know what to do with the partial result I'm returning. eg, `(lazy-recur 1 1)` will return "incorrect" results: `("())" ")()")`. But that's okay, because I only get into those situations when I know there's one open-paren waiting for me at a higher level in the stack, so to speak.

So, all that said, the simplest solution to get rid of your flatten-alike is https://gist.github.com/amalloy/2e7af7510d563b4345bd/80f800b5548af1e4f3811ddf6fa11a219bafb446 - just adding a couple levels of lists to regularize the nesting, followed by an apply concat, and lifting out the `set` call the to top level, once you've actually got all the answers, instead of constantly going in and out of sets.

**Comment by djtrack16** [comment]
I appreciate the advice, I'm not sure why the indentation was so
aggressive, but I've refactored a lot. I agree, dealing with strings in
clojure is a pain.

Any headway on the other submissions?
I have more problems ready, but I'll keep those on hold until someone has
had a chance to look at the others.

Also, if there are (or you have) guidelines for writing tests ( I guess
short problem descriptions are best?), then I can minimize the editing that
you all will have to do.
