### ISSUE TITLE
Feedback on Problems/Solutions

### ISSUE THREAD

**Issue by asthasr** [4clojure/4clojure#251]
It would be interesting to be able to interact with problems and solutions. For example, I recently finished problem #134, which is to detect whether a collection contains a given key and is nil. After solving, I looked at other users' solutions, and noticed that there is one that fails if another test is applied; it would be good for there to be a "Suggest a Test" function and, if the test is accepted, clear old solutions that don't pass the new test.

**Comment by amalloy** [comment]
This would be sorta an anti-feature IMO. It's a shame that we don't always construct perfect test cases: there are a number of quite old problems that have tests that are insufficient, and so some bad answers get through. But we basically decided to just live with that, because it's better than disqualifying people who solved the problem as written.
