### ISSUE TITLE
Working answer to #22 wont' get accepted

### ISSUE THREAD

**Issue by mikebelanger** [4clojure/4clojure#289]
Hi,

I'm just going through problem #22, where it asks to get the size of a collection without using `count`.  I've tested this solution in my local machine REPL (Planck):

`reduce + (map #(+ 0 1)`

*Note that I left out the first parenthesis because it looks like it's included already.

Anyways, not sure why it's not accepting.  It just gives an EOF return.  All the tests checkout:
`cljs.user=> (= (reduce + (map #(+ 0 1) '(1 2 3 3 1))) 5)
=> true`
`cljs.user=> (= (reduce + (map #(+ 0 1) "Hello World")) 11)
=>true`
`cljs.user=> (= (reduce + (map #(+ 0 1) [[1 2] [3 4] [5 6]])) 3)
=>true`
`cljs.user=> (= (reduce + (map #(+ 0 1) '(13))) 1)
=>true`
`cljs.user=> (= (reduce + (map #(+ 0 1) '(:a :b :c))) 3)
=>true`
`cljs.user=> (= (reduce + (map #(+ 0 1) [[1 2] [3 4] [5 6]])) 3)
=>true`

**Comment by jeaye** [comment]
The parens in each unit test for http://www.4clojure.com/problem/22 are all balanced. There's not a single 4clojure unit test I've seen which provides you with unbalanced code. You're expected to put a self-contained function within the `__`. You're getting an error because the code you've specified is not balanced.

**Comment by mikebelanger** [comment]
I see, thanks!
