### ISSUE TITLE
4clojure.com operating as a TOR node

### ISSUE THREAD

**Issue by oliverjensen-wk** [4clojure/4clojure#299]
4clojure.com is served off of 173.255.221.96 which is also operating as a TOR node (see https://torstatus.blutmagie.de/router_detail.php?FP=8b5d060d85e8aa28c34498c9ed763cefc0ba530d). If that's intentional, great, but I'm filing the issue in case it is not.

As an aside, operating as a TOR node may cause access issues from corporate networks.

**Comment by amalloy** [comment]
Yes, I do this on purpose. I agree with the goals of the Tor project, and I have much larger bandwidth and CPU budgets than I need, so I donate the spare by acting as a Tor node. I hadn't thought about the possibility of a corporation blocking a Tor middle node. I understand (but disagree with) servers blocking exit nodes because of abuse issues, but for a non-exit relay it didn't make much sense to me. I guess since we're also acting as an entry node, corporations may worry that enabling Tor access basically bypasses all of their other outbound firewall rules. Makes sense, I guess.

So far I haven't heard anyone complain of being unable to access 4clojure because of Tor issues, and I don't plan to change the setup.

Thanks for filing this issue: I can imagine it would be quite unpleasant to accidentally be a Tor node.
